services:
  walkin-proxy:
    container_name: walkin-proxy
    image: nginx:1.24.0
    restart: always
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "80:80"
      - "443:443"

  walkin-dashboard:
    container_name: dashboard
    image: localhost:5000/walkin-dashboard
    build:
      dockerfile: Dockerfile.local
      context: ./dashboard
    restart: always
    command:
      ['ash', '-c', 'npm i && npm run dev']
    working_dir: /app
    volumes:
      - ./dashboard:/app

  walkin-api:
    container_name: walkin-api
    image: node:20
    build: 
      context: ./api
    restart: always
    command:
      ["sh", "-c", "npm install && npm start"]
    working_dir: /app
    volumes:
      - ./api:/app
    env_file:
      - ./.env

  walkin-database:
    container_name: walkin-database
    image: mongo:4.2.24-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ADMIN_USERPASS}
      - MONGO_INITDB_DATABASE=walkin-database
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - walkin-database:/data/db
    
    ports:
      - 15088:27017

  # schd-ddb-manager:
  #   container_name: schd-db-manager
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 19081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_URL=mongodb://${DB_ADMIN_USERNAME}:${DB_ADMIN_USERPASS}@schd-database:27017/?authSource=admin

volumes:
  walkin-database:

networks:
  default: