# Used for local development
#
#   docker build -t localhost:5000/udo-notifier-frontend-local -f Dockerfile.local .
#   docker run --rm -it --name udo-frontend-local -v `pwd`:/app -p 3000:3000  localhost:5000/udo-notifier-frontend-local ash
#
FROM node:20.2.0-alpine3.17

WORKDIR /app